[package]
name = "mighty-hooks-dispatch"
version = "0.1.0"
edition = "2021"

[dependencies]
mighty-hooks-config = { path = "../config" }
mighty-hooks-core = { path = "../core" }
log = "0.4"
reqwest = "^0.11.14"
bytes = "^1.4.0"
futures = "^0.3.26"
